language: android
sudo: required
dist: precise
jdk: oraclejdk8

before_cache:
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock # Avoid to repack it due locks
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/classAnalysis/classAnalysis.lock
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/3.3/jarSnapshots/jarSnapshots.lock

install:
  # List and delete unnecessary components to free space
  - sdkmanager --list || true
  - sdkmanager --uninstall "system-images;android-14;default;x86"
  - sdkmanager --uninstall "system-images;android-15;default;x86"
  - sdkmanager --uninstall "system-images;android-16;default;x86"
  - sdkmanager --uninstall "system-images;android-17;default;x86"
  - sdkmanager --uninstall "system-images;android-18;default;x86"
  - sdkmanager --uninstall "system-images;android-19;default;x86"
  - sdkmanager --uninstall "system-images;android-21;default;x86"
  - sdkmanager --uninstall "system-images;android-22;default;x86"
  - sdkmanager --uninstall "system-images;android-23;default;x86"
  - sdkmanager --uninstall "system-images;android-24;default;x86"
  - sdkmanager --uninstall "system-images;android-25;default;x86"
  - sdkmanager --uninstall "system-images;android-26;default;x86"
  
  - sdkmanager --uninstall "extras;google;google_play_services"
  - sdkmanager --uninstall "extras;android;support"
  - sdkmanager --uninstall "platforms;android-10"
  - sdkmanager --uninstall "platforms;android-14"
  - sdkmanager --uninstall "platforms;android-15"
  - sdkmanager --uninstall "platforms;android-16"
  - sdkmanager --uninstall "platforms;android-17"
  - sdkmanager --uninstall "platforms;android-18"
  - sdkmanager --uninstall "platforms;android-19"
  - sdkmanager --uninstall "platforms;android-20"
  - sdkmanager --uninstall "platforms;android-21"
  - sdkmanager --uninstall "platforms;android-22"
  - sdkmanager --uninstall "platforms;android-23"
  - sdkmanager --uninstall "platforms;android-24"
  - sdkmanager --uninstall "platforms;android-25"
  - sdkmanager --uninstall "platforms;android-26"
  - sdkmanager --uninstall "build-tools;21.1.2"
  
   # Update sdk tools to latest version and install/update components
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-25" # Latest platform required by SDK tools
  - echo yes | sdkmanager "platforms;android-${API}" # Android platform required by emulator
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - echo yes | sdkmanager "$EMULATOR" # Install emulator system image
 
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-26.0.1
  - echo y | android update sdk -u -a -t android-26
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
  - echo y | android update sdk -u -a -t android-sdk-preview-license
  - echo y | android update sdk -u -a -t android-sdk-license
  
# Create and start emulator
  - echo no | avdmanager create avd -n acid -k "$EMULATOR" -f --abi "$ANDROID_ABI"
  - emulator -avd acid -engine classic -no-window -camera-back none -camera-front none -verbose -qemu -m 512 &
  # Start adbd, wait for device connected and show android serial
  - adb wait-for-device get-serialno
  # Show version and download Gradle Wrapper if it's not already cached
  - cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew --version
  # Clean project and download missing dependencies and components
  - cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew clean build
  # Check components status
  - sdkmanager --list || true

env:
  global:
    - ADB_INSTALL_TIMEOUT=35 # minutes
  matrix:
    - ANDROID_TARGET=android-14  ANDROID_ABI=x86
    - ANDROID_TARGET=android-15  ANDROID_ABI=x86
    - ANDROID_TARGET=android-16  ANDROID_ABI=x86
    - ANDROID_TARGET=android-17  ANDROID_ABI=x86
    - ANDROID_TARGET=android-18  ANDROID_ABI=x86
    - ANDROID_TARGET=android-19  ANDROID_ABI=x86
    - ANDROID_TARGET=android-20  ANDROID_ABI=x86
    - ANDROID_TARGET=android-21  ANDROID_ABI=x86
    - ANDROID_TARGET=android-22  ANDROID_ABI=x86
    # no android-23 yet 20150925
    - ANDROID_TARGET=android-23  ANDROID_ABI=x86
    - ANDROID_TARGET=android-24  ANDROID_ABI=x86
    - ANDROID_TARGET=android-25  ANDROID_ABI=x86
    - ANDROID_TARGET=android-26  ANDROID_ABI=x86
    
android:
  components:
  #  - build-tools-19.0.0
    - build-tools-26
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    
    - android-14
    #- sys-img-armeabi-v7a-android-14
    - sys-img-x86-android-14
    - android-15
    #- sys-img-armeabi-v7a-android-15
    - sys-img-x86-android-15
    - android-16
    #- sys-img-armeabi-v7a-android-16
    - sys-img-x86-android-16
    - android-17
    #- sys-img-armeabi-v7a-android-17
    - sys-img-x86-android-17
    - android-18
    #- sys-img-armeabi-v7a-android-18
    - sys-img-x86-android-18
    - android-19
    #- sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-19
    - android-20
    #- sys-img-armeabi-v7a-android-20
    - sys-img-x86-android-20
    - android-21
    #- sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-21
    - android-22
    #- sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-22
    - android-23
    #- sys-img-armeabi-v7a-android-23
    - sys-img-x86-android-23
    - android-24
    #- sys-img-armeabi-v7a-android-24
    - sys-img-x86-android-24
    - android-25
    #- sys-img-armeabi-v7a-android-25
    - sys-img-x86-android-25
    - android-26
    #- sys-img-armeabi-v7a-android-26
    - sys-img-x86-android-26

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

before_script:
  # Create and start emulator
  - echo PATH $PATH
  - android list target

  - android list sdk
  - which android-update-sdk
  - cat `which android-update-sdk`
  - android-update-sdk
  - android list sdk --all --extended
# install other componets.
#  - android-update-sdk --components=build-tools-21.1.1
#  - android list sdk --all --extended | grep id:

  - uname -a
  - df -h
  - mount
  - chmod +x gradlew
  - cat /proc/cpuinfo
  - echo $ANDROID_TARGET
  - echo $ANDROID_ABI
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -wipe-data
#  - emulator -avd test -no-skin -no-window &
#  - adb wait-for-device
  - cat `which android-wait-for-emulator`
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - sleep 30
  - adb shell input keyevent 82 &

script:
- "./gradlew clean build cAT"
