language: android
sudo: required
dist: precise
jdk: oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-26.0.1
  - echo y | android update sdk -u -a -t android-26
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
  - echo y | android update sdk -u -a -t android-sdk-preview-license
  - echo y | android update sdk -u -a -t android-sdk-license

env:
  global:
    - ADB_INSTALL_TIMEOUT=30 # minutes
  matrix:
    - ANDROID_TARGET=android-4  ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-5  ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-6  ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-7  ANDROID_ABI=armeabi
    #- ANDROID_TARGET=android-8  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-8  ANDROID_ABI=armeabi
    #- ANDROID_TARGET=android-9  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-9  ANDROID_ABI=armeabi
    #- ANDROID_TARGET=android-10  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-10  ANDROID_ABI=armeabi

    # 11, 12, 13, 14 often fail.
    #- ANDROID_TARGET=android-11  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-11  ANDROID_ABI=armeabi
    #- ANDROID_TARGET=android-12  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-12  ANDROID_ABI=armeabi
    #- ANDROID_TARGET=android-13  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-13  ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-14  ANDROID_ABI=armeabi-v7a

    - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-18  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-20  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
    # no android-23 yet 20150925
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
  components:
  #  - build-tools-19.0.0
    - build-tools-26
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
    - android-4
    - sys-img-armeabi-android-4
    - android-5
    - sys-img-armeabi-android-5
    - android-6
    - sys-img-armeabi-android-6
    - android-7
    - sys-img-armeabi-android-7
    - android-8
    - sys-img-armeabi-android-8
    #- sys-img-x86-android-8
    - android-9
    - sys-img-armeabi-android-9
    #- sys-img-x86-android-9
    - android-10
    - sys-img-armeabi-android-10
    #- sys-img-x86-android-10
    - android-11
    - sys-img-armeabi-android-11
    #- sys-img-x86-android-11
    - android-12
    - sys-img-armeabi-android-12
    #- sys-img-x86-android-12
    - android-13
    - sys-img-armeabi-v7a-android-13
    #- sys-img-x86-android-13
    - android-14
    - sys-img-armeabi-v7a-android-14
    #- sys-img-x86-android-14
    - android-15
    - sys-img-armeabi-v7a-android-15
    #- sys-img-x86-android-15
    - android-16
    - sys-img-armeabi-v7a-android-16
    #- sys-img-x86-android-16
    - android-17
    - sys-img-armeabi-v7a-android-17
    #- sys-img-x86-android-17
    - android-18
    - sys-img-armeabi-v7a-android-18
    #- sys-img-x86-android-18
    - android-19
    - sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-19
    - android-20
    - sys-img-armeabi-v7a-android-20
    #- sys-img-x86-android-20
    - android-21
    - sys-img-armeabi-v7a-android-21
    #- sys-img-x86-android-21
    - android-22
    - sys-img-armeabi-v7a-android-22
    #- sys-img-x86-android-22
    - android-23
    - sys-img-armeabi-v7a-android-23
    #- sys-img-x86-android-23
    - android-24
    - sys-img-armeabi-v7a-android-24
    #- sys-img-x86-android-24
    - android-25
    - sys-img-armeabi-v7a-android-25
    #- sys-img-x86-android-25
    - android-26
    - sys-img-armeabi-v7a-android-26
    #- sys-img-x86-android-26

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

before_script:
  # Create and start emulator
  - echo PATH $PATH
  - android list target

  - android list sdk
  - which android-update-sdk
  - cat `which android-update-sdk`
  - android-update-sdk
  - android list sdk --all --extended
# install other componets.
#  - android-update-sdk --components=build-tools-21.1.1
#  - android list sdk --all --extended | grep id:

  - uname -a
  - df -h
  - mount
  - chmod +x gradlew
  - cat /proc/cpuinfo
  - echo $ANDROID_TARGET
  - echo $ANDROID_ABI
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - cat `which android-wait-for-emulator`
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script:
- "./gradlew cAT"
